import Head from 'next/head';
import Image from 'next/image';
import { NavBar } from '../components/Header/App';
import styles from '../styles/Home.module.css';
import { Hero } from '../components/Hero/App';
import { Features } from '../components/Features/App';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Hero />
        <Features />
      </main>
    </div>
  );
}
